import * as vscode from 'vscode';
import { SupportedUiLocale, uiLocale, webviewStrings, WebviewStrings } from './localization';

const EXTRAS: Record<SupportedUiLocale, WebviewStrings> = {
  'zh-cn': {
    annotationModeLabel: '标注模式',
    modeTemplate: '模板',
    modeRect: '框',
    modePoint: '点',
    sharedHistory: '共享撤销历史',
    sharedHistoryTooltip: '模板、框和点模式共用撤销/重做历史',
    coordPreferenceTooltip: '未勾选：x1,y1,x2,y2；勾选：x,y,w,h。也用于解释没有名称的四数字粘贴。',
    pointTool: '点 ({key})',
    newPointTitle: '新建点',
    editPointTitle: '编辑点',
    clipboardInvalid: '剪贴板内容不是有效的归一化坐标。',
    clipboardPointOnly: '零尺寸坐标只能在点模式中粘贴。',
    positionPathFailed: '位置路径无效',
    conflictTitle: '标注冲突',
    conflictCurrent: '当前编辑',
    conflictExternal: '外部修改',
    conflictFields: '冲突字段',
    conflictApply: '应用选择并保存',
    conflictHint: '两边都会保留到你完成选择；未解决前不会写盘。',
  },
  'zh-tw': {
    annotationModeLabel: '標註模式',
    modeTemplate: '模板',
    modeRect: '框',
    modePoint: '點',
    sharedHistory: '共用復原歷史',
    sharedHistoryTooltip: '模板、框和點模式共用復原/重做歷史',
    coordPreferenceTooltip: '未勾選：x1,y1,x2,y2；勾選：x,y,w,h。也用於解讀沒有名稱的四數字貼上。',
    pointTool: '點 ({key})',
    newPointTitle: '新增點',
    editPointTitle: '編輯點',
    clipboardInvalid: '剪貼簿內容不是有效的正規化座標。',
    clipboardPointOnly: '零尺寸座標只能在點模式中貼上。',
    positionPathFailed: '位置路徑無效',
    conflictTitle: '標註衝突',
    conflictCurrent: '目前編輯',
    conflictExternal: '外部修改',
    conflictFields: '衝突欄位',
    conflictApply: '套用選擇並儲存',
    conflictHint: '完成選擇前會保留兩個版本；衝突未解決前不會寫入磁碟。',
  },
  en: {
    annotationModeLabel: 'Annotation mode',
    modeTemplate: 'Template',
    modeRect: 'Box',
    modePoint: 'Point',
    sharedHistory: 'Shared undo history',
    sharedHistoryTooltip: 'Share undo/redo history between Template, Box and Point modes',
    coordPreferenceTooltip: 'Unchecked: x1,y1,x2,y2. Checked: x,y,w,h. Also resolves ambiguous unnamed four-number pastes.',
    pointTool: 'Point ({key})',
    newPointTitle: 'New Point',
    editPointTitle: 'Edit Point',
    clipboardInvalid: 'Clipboard is not a valid normalized coordinate tuple.',
    clipboardPointOnly: 'Zero-size coordinates can only be pasted in Point mode.',
    positionPathFailed: 'Invalid position path',
    conflictTitle: 'Annotation conflicts',
    conflictCurrent: 'Current edit',
    conflictExternal: 'External change',
    conflictFields: 'Conflicting fields',
    conflictApply: 'Apply choices and save',
    conflictHint: 'Both versions are kept until every conflict is resolved; nothing is written before that.',
  },
  ja: {
    annotationModeLabel: 'アノテーションモード',
    modeTemplate: 'テンプレート',
    modeRect: 'ボックス',
    modePoint: 'ポイント',
    sharedHistory: '取り消し履歴を共有',
    sharedHistoryTooltip: 'テンプレート・ボックス・ポイントで取り消し/やり直し履歴を共有します',
    coordPreferenceTooltip: '未選択: x1,y1,x2,y2。選択: x,y,w,h。名前なしの4数値貼り付けの解釈にも使います。',
    pointTool: 'ポイント ({key})',
    newPointTitle: '新しいポイント',
    editPointTitle: 'ポイントを編集',
    clipboardInvalid: 'クリップボードの内容は有効な正規化座標ではありません。',
    clipboardPointOnly: 'サイズ 0 の座標はポイントモードでのみ貼り付けできます。',
    positionPathFailed: '位置パスが無効です',
    conflictTitle: 'アノテーション競合',
    conflictCurrent: '現在の編集',
    conflictExternal: '外部変更',
    conflictFields: '競合フィールド',
    conflictApply: '選択を適用して保存',
    conflictHint: 'すべての競合を解決するまで両方のバージョンを保持し、その前には書き込みません。',
  },
  ko: {
    annotationModeLabel: '주석 모드',
    modeTemplate: '템플릿',
    modeRect: '박스',
    modePoint: '포인트',
    sharedHistory: '실행 취소 기록 공유',
    sharedHistoryTooltip: '템플릿, 박스, 포인트 모드가 실행 취소/다시 실행 기록을 공유합니다',
    coordPreferenceTooltip: '해제: x1,y1,x2,y2. 선택: x,y,w,h. 이름 없는 네 숫자 붙여넣기 해석에도 사용합니다.',
    pointTool: '포인트 ({key})',
    newPointTitle: '새 포인트',
    editPointTitle: '포인트 편집',
    clipboardInvalid: '클립보드 내용이 유효한 정규화 좌표가 아닙니다.',
    clipboardPointOnly: '크기가 0인 좌표는 포인트 모드에서만 붙여넣을 수 있습니다.',
    positionPathFailed: '잘못된 위치 경로',
    conflictTitle: '주석 충돌',
    conflictCurrent: '현재 편집',
    conflictExternal: '외부 변경',
    conflictFields: '충돌 필드',
    conflictApply: '선택 적용 및 저장',
    conflictHint: '모든 충돌을 해결할 때까지 두 버전을 모두 유지하며 그 전에는 파일에 쓰지 않습니다.',
  },
  es: {
    annotationModeLabel: 'Modo de anotación',
    modeTemplate: 'Plantilla',
    modeRect: 'Cuadro',
    modePoint: 'Punto',
    sharedHistory: 'Compartir historial de deshacer',
    sharedHistoryTooltip: 'Comparte el historial de deshacer/rehacer entre Plantilla, Cuadro y Punto',
    coordPreferenceTooltip: 'Desmarcado: x1,y1,x2,y2. Marcado: x,y,w,h. También resuelve pegados ambiguos de cuatro números sin nombre.',
    pointTool: 'Punto ({key})',
    newPointTitle: 'Nuevo punto',
    editPointTitle: 'Editar punto',
    clipboardInvalid: 'El contenido del portapapeles no es una coordenada normalizada válida.',
    clipboardPointOnly: 'Las coordenadas de tamaño cero solo se pueden pegar en el modo Punto.',
    positionPathFailed: 'Ruta de posición no válida',
    conflictTitle: 'Conflicto de anotaciones',
    conflictCurrent: 'Edición actual',
    conflictExternal: 'Cambio externo',
    conflictFields: 'Campos en conflicto',
    conflictApply: 'Aplicar selección y guardar',
    conflictHint: 'Se conservan ambas versiones hasta resolver todos los conflictos; antes no se escribe nada.',
  },
};

export function annotationWebviewStrings(language = vscode.env.language): WebviewStrings {
  return { ...webviewStrings(language), ...EXTRAS[uiLocale(language)] };
}

export function injectAnnotationWebviewLocalization(html: string, marker = '__I18N_JSON__'): string {
  return html.split(marker).join(JSON.stringify(annotationWebviewStrings()).replace(/</g, '\\u003c'));
}
