import * as fs from 'fs';
import * as path from 'path';
import { authoringReadErrors, readAuthoringFile } from './boxResourceStore';
import { pointAuthoringPositions } from './pointResourceStore';
import {
  PositionAuthoringItem,
  PositionImage,
  RuntimePositionFile,
  publishPositions,
  serializePositionJson,
  serializePositionMapPython,
  serializeScreenRatioPython,
} from './positionResourcePure';
import { writeAnnotationText } from './cocoAnnotationData';

export const GENERATED_MARKER = '# Generated by ok-script-toolkit. Do not edit manually.';
export const DEFAULT_POSITION_JSON = 'src/scene/positions.json';
export const DEFAULT_POSITION_PY_DIR = 'src/scene';

export type PositionPublishFormat = 'json' | 'python';

export interface PositionResourceSelection {
  rect: boolean;
  point: boolean;
}

export interface PositionPublishOptions extends PositionResourceSelection {
  jsonTarget: string;
  pythonTargetDir: string;
  overwriteManual?: boolean;
}

export interface PositionPublishResult {
  ok: boolean;
  errors: string[];
  files: string[];
  protectedFiles?: string[];
}

interface FileSnapshot {
  exists: boolean;
  text?: string;
}

function imageKey(name: string): string {
  return path.basename(name).toLowerCase();
}

/** Conflicts in the single exported PositionMap namespace, regardless of authoring resource kind. */
export function positionNamespaceConflicts(
  selectedPaths: readonly string[],
  otherPaths: readonly string[],
): string[] {
  const errors = new Set<string>();
  for (const selectedRaw of selectedPaths) {
    const selected = selectedRaw.trim();
    if (!selected) continue;
    for (const otherRaw of otherPaths) {
      const other = otherRaw.trim();
      if (!other) continue;
      if (selected === other) {
        errors.add(`duplicate:${selected}`);
      } else if (selected.startsWith(`${other}.`) || other.startsWith(`${selected}.`)) {
        errors.add(`prefix:${selected}`);
      }
    }
  }
  return [...errors];
}

export function collectPositionRuntime(
  root: string,
  directory: string,
  selection: PositionResourceSelection,
): { file: RuntimePositionFile; errors: string[] } {
  if (!selection.rect && !selection.point) {
    return { file: { version: 2, positions: [] }, errors: ['selection'] };
  }

  const images = new Map<string, PositionImage>();
  const items: PositionAuthoringItem[] = [];

  if (selection.rect) {
    const boxErrors = authoringReadErrors(root, directory);
    if (boxErrors.length) {
      return { file: { version: 2, positions: [] }, errors: boxErrors.map(error => `boxes:${error}`) };
    }
    const boxes = readAuthoringFile(root, directory);
    for (const image of boxes.images) {
      images.set(imageKey(image.file), {
        file: path.basename(image.file),
        width: image.width,
        height: image.height,
      });
    }
    items.push(...boxes.boxes.map(box => ({
      path: box.path,
      image: path.basename(box.image),
      kind: 'rect' as const,
      rect: { x: box.bbox[0], y: box.bbox[1], w: box.bbox[2], h: box.bbox[3] },
    })));
  }

  if (selection.point) {
    const points = pointAuthoringPositions(root, directory);
    if (points.errors.length) {
      return { file: { version: 2, positions: [] }, errors: points.errors.map(error => `points:${error}`) };
    }
    for (const image of points.images) {
      const key = imageKey(image.file);
      const existing = images.get(key);
      if (existing && (existing.width !== image.width || existing.height !== image.height)) {
        return { file: { version: 2, positions: [] }, errors: [`imageSize:${image.file}`] };
      }
      images.set(key, {
        file: path.basename(image.file),
        width: image.width,
        height: image.height,
      });
    }
    items.push(...points.items.map(item => ({ ...item, image: path.basename(item.image) })));
  }

  // A partial export still writes the complete output file. Check the shared namespace against the
  // unselected catalog when that catalog is readable, but do not let an invalid unselected source
  // block an intentionally isolated Rect-only / Point-only publish.
  if (selection.rect !== selection.point) {
    const selectedPaths = items.map(item => item.path);
    let otherPaths: string[] = [];
    if (selection.rect) {
      const points = pointAuthoringPositions(root, directory);
      if (!points.errors.length) otherPaths = points.items.map(item => item.path);
    } else {
      const boxErrors = authoringReadErrors(root, directory);
      if (!boxErrors.length) otherPaths = readAuthoringFile(root, directory).boxes.map(box => box.path);
    }
    const conflicts = positionNamespaceConflicts(selectedPaths, otherPaths);
    if (conflicts.length) return { file: { version: 2, positions: [] }, errors: conflicts };
  }

  return publishPositions(items, [...images.values()]);
}

function isInside(base: string, candidate: string): boolean {
  const rel = path.relative(base, candidate);
  return rel === '' || (rel !== '..' && !rel.startsWith(`..${path.sep}`) && !path.isAbsolute(rel));
}

function realpath(file: string): string {
  return fs.realpathSync.native ? fs.realpathSync.native(file) : fs.realpathSync(file);
}

/** Lexical containment is not enough: reject existing symlink/junction ancestors that resolve outside the project. */
function ensureInsideRoot(root: string, relative: string): string | undefined {
  const resolvedRoot = path.resolve(root);
  const target = path.resolve(resolvedRoot, relative);
  if (!isInside(resolvedRoot, target) || target === resolvedRoot) return undefined;

  let realRoot: string;
  try { realRoot = realpath(resolvedRoot); } catch { return undefined; }

  let existing = target;
  while (!fs.existsSync(existing)) {
    const parent = path.dirname(existing);
    if (parent === existing) return undefined;
    existing = parent;
  }

  let realExisting: string;
  try { realExisting = realpath(existing); } catch { return undefined; }
  if (!isInside(realRoot, realExisting)) return undefined;
  return target;
}

function isGeneratedPython(file: string): boolean {
  if (!fs.existsSync(file)) return true;
  try {
    return fs.readFileSync(file, 'utf8').startsWith(GENERATED_MARKER);
  } catch {
    return false;
  }
}

/**
 * Preserve the historical default JSON replacement behavior, but require explicit confirmation
 * before a configurable JSON target replaces an existing project file.
 */
export function positionJsonRequiresOverwriteConfirmation(relativeTarget: string, exists: boolean): boolean {
  const normalized = relativeTarget.replace(/\\/g, '/').replace(/^(?:\.?\/)+/, '').replace(/\/+$/, '');
  return exists && normalized !== DEFAULT_POSITION_JSON;
}

function atomicWrite(file: string, text: string): void {
  writeAnnotationText(file, text, false);
}

function snapshotText(file: string): FileSnapshot {
  if (!fs.existsSync(file)) return { exists: false };
  return { exists: true, text: fs.readFileSync(file, 'utf8') };
}

function restoreSnapshot(file: string, snapshot: FileSnapshot): boolean {
  try {
    if (snapshot.exists) atomicWrite(file, snapshot.text ?? '');
    else fs.rmSync(file, { force: true });
    return true;
  } catch {
    return false;
  }
}

export function publishPositionJson(
  root: string,
  directory: string,
  selection: PositionResourceSelection,
  relativeTarget: string,
  overwriteExisting = false,
): PositionPublishResult {
  const projected = collectPositionRuntime(root, directory, selection);
  if (projected.errors.length) return { ok: false, errors: projected.errors, files: [] };
  if (!projected.file.positions.length) return { ok: false, errors: ['empty'], files: [] };
  const target = ensureInsideRoot(root, relativeTarget);
  if (!target) return { ok: false, errors: ['target'], files: [] };
  if (positionJsonRequiresOverwriteConfirmation(relativeTarget, fs.isFileSync(target)) && !overwriteExisting) {
    return { ok: false, errors: ['manual'], files: [], protectedFiles: [target] };
  }
  try {
    atomicWrite(target, serializePositionJson(projected.file));
    return { ok: true, errors: [], files: [target] };
  } catch {
    return { ok: false, errors: ['write'], files: [] };
  }
}

export function publishPositionPython(
  root: string,
  directory: string,
  selection: PositionResourceSelection,
  relativeTargetDir: string,
  overwriteManual = false,
): PositionPublishResult {
  const projected = collectPositionRuntime(root, directory, selection);
  if (projected.errors.length) return { ok: false, errors: projected.errors, files: [] };
  if (!projected.file.positions.length) return { ok: false, errors: ['empty'], files: [] };
  const targetDir = ensureInsideRoot(root, relativeTargetDir);
  if (!targetDir) return { ok: false, errors: ['target'], files: [] };
  const ratioFile = path.join(targetDir, 'ScreenRatio.py');
  const mapFile = path.join(targetDir, 'PositionMap.py');
  const protectedFiles = [ratioFile, mapFile].filter(file => !isGeneratedPython(file));
  if (protectedFiles.length && !overwriteManual) {
    return { ok: false, errors: ['manual'], files: [], protectedFiles };
  }

  let ratioBefore: FileSnapshot;
  let mapBefore: FileSnapshot;
  try {
    ratioBefore = snapshotText(ratioFile);
    mapBefore = snapshotText(mapFile);
  } catch {
    return { ok: false, errors: ['write'], files: [] };
  }

  try {
    fs.mkdirSync(targetDir, { recursive: true });
    atomicWrite(ratioFile, serializeScreenRatioPython());
    atomicWrite(mapFile, serializePositionMapPython(projected.file));
    return { ok: true, errors: [], files: [ratioFile, mapFile] };
  } catch {
    const restored = restoreSnapshot(ratioFile, ratioBefore) && restoreSnapshot(mapFile, mapBefore);
    return { ok: false, errors: [restored ? 'write' : 'write:rollback'], files: [] };
  }
}

export function publishPositionsByFormat(
  root: string,
  directory: string,
  format: PositionPublishFormat,
  options: PositionPublishOptions,
): PositionPublishResult {
  const selection = { rect: options.rect, point: options.point };
  return format === 'python'
    ? publishPositionPython(root, directory, selection, options.pythonTargetDir, options.overwriteManual ?? false)
    : publishPositionJson(root, directory, selection, options.jsonTarget, options.overwriteManual ?? false);
}
