import * as fs from 'fs';
import * as path from 'path';
import { readAuthoringFile } from './boxResourceStore';
import { pointAuthoringPositions } from './pointResourceStore';
import {
  PositionAuthoringItem,
  PositionImage,
  RuntimePositionFile,
  publishPositions,
  serializePositionJson,
  serializePositionMapPython,
  serializeScreenRatioPython,
} from './positionResourcePure';
import { writeAnnotationText } from './cocoAnnotationData';

export const GENERATED_MARKER = '# Generated by ok-script-toolkit. Do not edit manually.';
export const DEFAULT_POSITION_JSON = 'src/scene/positions.json';
export const DEFAULT_POSITION_PY_DIR = 'src/scene';

export type PositionPublishFormat = 'json' | 'python';

export interface PositionPublishResult {
  ok: boolean;
  errors: string[];
  files: string[];
  protectedFiles?: string[];
}

interface FileSnapshot {
  exists: boolean;
  text?: string;
}

function imageKey(name: string): string {
  return path.basename(name).toLowerCase();
}

export function collectPositionRuntime(root: string, directory: string): { file: RuntimePositionFile; errors: string[] } {
  const boxes = readAuthoringFile(root, directory);
  const points = pointAuthoringPositions(root, directory);
  if (points.errors.length) return { file: { version: 2, positions: [] }, errors: points.errors.map(error => `points:${error}`) };

  const images = new Map<string, PositionImage>();
  for (const image of boxes.images) {
    images.set(imageKey(image.file), { file: path.basename(image.file), width: image.width, height: image.height });
  }
  for (const image of points.images) {
    const key = imageKey(image.file);
    const existing = images.get(key);
    if (existing && (existing.width !== image.width || existing.height !== image.height)) {
      return { file: { version: 2, positions: [] }, errors: [`imageSize:${image.file}`] };
    }
    images.set(key, { file: path.basename(image.file), width: image.width, height: image.height });
  }

  const items: PositionAuthoringItem[] = boxes.boxes.map(box => ({
    path: box.path,
    image: path.basename(box.image),
    kind: 'rect',
    rect: { x: box.bbox[0], y: box.bbox[1], w: box.bbox[2], h: box.bbox[3] },
  }));
  items.push(...points.items.map(item => ({ ...item, image: path.basename(item.image) })));

  return publishPositions(items, [...images.values()]);
}

function isInside(base: string, candidate: string): boolean {
  const rel = path.relative(base, candidate);
  return rel === '' || (rel !== '..' && !rel.startsWith(`..${path.sep}`) && !path.isAbsolute(rel));
}

function realpath(file: string): string {
  return fs.realpathSync.native ? fs.realpathSync.native(file) : fs.realpathSync(file);
}

/** Lexical containment is not enough: reject existing symlink/junction ancestors that resolve outside the project. */
function ensureInsideRoot(root: string, relative: string): string | undefined {
  const resolvedRoot = path.resolve(root);
  const target = path.resolve(resolvedRoot, relative);
  if (!isInside(resolvedRoot, target) || target === resolvedRoot) return undefined;

  let realRoot: string;
  try { realRoot = realpath(resolvedRoot); } catch { return undefined; }

  let existing = target;
  while (!fs.existsSync(existing)) {
    const parent = path.dirname(existing);
    if (parent === existing) return undefined;
    existing = parent;
  }

  let realExisting: string;
  try { realExisting = realpath(existing); } catch { return undefined; }
  if (!isInside(realRoot, realExisting)) return undefined;
  return target;
}

function isGeneratedPython(file: string): boolean {
  if (!fs.existsSync(file)) return true;
  try {
    return fs.readFileSync(file, 'utf8').startsWith(GENERATED_MARKER);
  } catch {
    return false;
  }
}

function atomicWrite(file: string, text: string): void {
  writeAnnotationText(file, text, false);
}

function snapshotText(file: string): FileSnapshot {
  if (!fs.existsSync(file)) return { exists: false };
  return { exists: true, text: fs.readFileSync(file, 'utf8') };
}

function restoreSnapshot(file: string, snapshot: FileSnapshot): boolean {
  try {
    if (snapshot.exists) atomicWrite(file, snapshot.text ?? '');
    else fs.rmSync(file, { force: true });
    return true;
  } catch {
    return false;
  }
}

export function publishPositionJson(
  root: string,
  directory: string,
  relativeTarget = DEFAULT_POSITION_JSON,
): PositionPublishResult {
  const projected = collectPositionRuntime(root, directory);
  if (projected.errors.length) return { ok: false, errors: projected.errors, files: [] };
  if (!projected.file.positions.length) return { ok: false, errors: ['empty'], files: [] };
  const target = ensureInsideRoot(root, relativeTarget);
  if (!target) return { ok: false, errors: ['target'], files: [] };
  try {
    atomicWrite(target, serializePositionJson(projected.file));
    return { ok: true, errors: [], files: [target] };
  } catch {
    return { ok: false, errors: ['write'], files: [] };
  }
}

export function publishPositionPython(
  root: string,
  directory: string,
  relativeTargetDir = DEFAULT_POSITION_PY_DIR,
  overwriteManual = false,
): PositionPublishResult {
  const projected = collectPositionRuntime(root, directory);
  if (projected.errors.length) return { ok: false, errors: projected.errors, files: [] };
  if (!projected.file.positions.length) return { ok: false, errors: ['empty'], files: [] };
  const targetDir = ensureInsideRoot(root, relativeTargetDir);
  if (!targetDir) return { ok: false, errors: ['target'], files: [] };
  const ratioFile = path.join(targetDir, 'ScreenRatio.py');
  const mapFile = path.join(targetDir, 'PositionMap.py');
  const protectedFiles = [ratioFile, mapFile].filter(file => !isGeneratedPython(file));
  if (protectedFiles.length && !overwriteManual) {
    return { ok: false, errors: ['manual'], files: [], protectedFiles };
  }

  let ratioBefore: FileSnapshot;
  let mapBefore: FileSnapshot;
  try {
    ratioBefore = snapshotText(ratioFile);
    mapBefore = snapshotText(mapFile);
  } catch {
    return { ok: false, errors: ['write'], files: [] };
  }

  try {
    fs.mkdirSync(targetDir, { recursive: true });
    atomicWrite(ratioFile, serializeScreenRatioPython());
    atomicWrite(mapFile, serializePositionMapPython(projected.file));
    return { ok: true, errors: [], files: [ratioFile, mapFile] };
  } catch {
    const restored = restoreSnapshot(ratioFile, ratioBefore) && restoreSnapshot(mapFile, mapBefore);
    return { ok: false, errors: [restored ? 'write' : 'write:rollback'], files: [] };
  }
}

export function publishPositionsByFormat(
  root: string,
  directory: string,
  format: PositionPublishFormat,
  overwriteManual = false,
): PositionPublishResult {
  return format === 'python'
    ? publishPositionPython(root, directory, DEFAULT_POSITION_PY_DIR, overwriteManual)
    : publishPositionJson(root, directory, DEFAULT_POSITION_JSON);
}
